---
services:
  - docker

env:
  - distribution: centos
    version: "7"
    repository: mariadb_repository
  - distribution: centos
    version: "6"
    repository: mariadb_repository
  - distribution: fedora
    version: "28"
    repository: mariadb_repository
  - distribution: fedora
    version: "27"
    repository: mariadb_repository
  - distribution: ubuntu
    version: "18.04"
    repository: mariadb_repository
  - distribution: ubuntu
    version: "17.10"
    repository: mariadb_repository
  - distribution: ubuntu
    version: "16.04"
    repository: mariadb_repository
  - distribution: ubuntu
    version: "14.04"
    repository: mariadb_repository
  - distribution: debian
    version: "9"
    repository: mariadb_repository
  - distribution: debian
    version: "8"
    repository: mariadb_repository
  - distribution: opensuse
    version: "42.3"
    repository: mariadb_repository
  - distribution: oraclelinux
    version: "7"
    repository: os_repository

before_install:
  # Build docker container
  - 'sudo docker pull diodonfrost/${distribution}-${version}-ansible:latest'

script:
  - container_id=$(mktemp)

  # Run container and mount ansible role with it
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-mariadb:ro diodonfrost/${distribution}-${version}-ansible:latest > "${container_id}"'

  # Check syntax
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-mariadb/tests/test.yml --syntax-check --extra-vars "install_from=${repository}"'

  # Run ansible playbook
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-mariadb/tests/test.yml --extra-vars "install_from=${repository}"'

  # Test indempotence
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-mariadb/tests/test.yml --extra-vars "install_from=${repository}"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test role
  - 'inspec exec tests/inspec -t docker://$(cat ${container_id})'

  # Delete container
  - 'sudo docker rm -f "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
