---
# tasks file for ansible-role-mariadb

# Include variables and define needed variables.
- name: Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup tasks.
- include_tasks: "setup.yml"
