---
# add mariadb repository in Fedora

- name: Add mariadb repository for Fedora
  yum_repository:
    name: MariaDB
    description: Maridb repository
    baseurl: "{{ fedora_repository }}"
    gpgcheck: true
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
