---
# add mariadb repository in Opensuse Leap

- name: Add mariadb rpm key
  rpm_key:
    state: present
    key: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

- name: Add mariadb repository for OpenSuse
  zypper_repository:
    name: MariaDB
    description: Maridb repository
    repo: "{{ openSUSE_repository }}"
    auto_import_keys: yes
    state: present
  when: ansible_distribution_major_version == "42"

- name: Add mariadb repository for OpenSuse
  zypper_repository:
    name: MariaDB
    description: Maridb repository
    repo: "https://yum.mariadb.org/{{ mariadb_version }}/opensuse/{{ ansible_distribution_major_version }}/x86_64"
    auto_import_keys: yes
    state: present
  when: ansible_distribution_major_version == "15"
