---
# add mariadb repository in Debian

- name: Add mariadb apt key
  apt_key:
    id: "{{ item }}"
    keyserver: keyserver.ubuntu.com
  with_items: " {{ ubuntu_repository_id }}"

- name: Add mariadb repository
  apt_repository:
    repo: deb [arch=i386,ppc64el,amd64] http://mariadb.mirrors.ovh.net/MariaDB/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main
    state: present
